# Generated by Django 3.0.1 on 2022-05-10 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='rainfalldetail',
            name='addon',
        ),
    ]
